# Версия docker-compose, которую мы используем. Зависит от установленной версии docker
version: '3.9'

# Внутренняя сеть меж контейнерами
networks:
  inter-network:
    external: true
    name: inter_network

services:
  # БД-контейнер
  mariadb:
    # Сборка из образа MariaDB
    image: mariadb:11.4
    # Название контейнера для удобства
    container_name: mariadb_container
    # {Порт на хосте}:{Порт на стороне контейнера}
    ports:
      - "3316:3306"
    # При закрытии повторно запускается
    restart: always
    # Папки, в которых происходит дублирование файлов на сторонах >>> {на хосте}:{внутри контейнера}
    volumes:
      - ./src:/var/lib/mysql
    # Передача параметров из файла
    env_file:
      - .env
    networks:
      - inter-network